project:
  type: website

website:
  title: "Meriah L. DeJoseph, PhD"
  navbar:
    left:
      - text: About
        href: index.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: Outreach & Media
        href: outreach.qmd

format:
  html:
    theme: flatly
    css: styles.css
    include-in-header: fonts.html



